#!/bin/sh
# This script is only used for developement. It is removed by the
# distribution process.

set -e

OCAMLBUILD=${OCAMLBUILD:="ocamlbuild -tag debug -classic-display \
                          -use-ocamlfind \
                          -plugin-tag package(js_of_ocaml.ocamlbuild)"}

action ()
{
    case $1 in
        default) action lib;; 
        lib)
            action lib-os
            action lib-jsoo
            ;;
        lib-os)   $OCAMLBUILD -I src-os mtime.cma mtime.cmxa ;;
        lib-jsoo) $OCAMLBUILD -I src-jsoo mtime.cma mtime.cmxa ;;
        test) 
            action test-os
            action test-jsoo
            ;;
        test-os)   
            action lib
            $OCAMLBUILD -I src-os test-os/tests.otarget
            ;;
        test-jsoo)
            action lib-jsoo
            $OCAMLBUILD -I src-jsoo test-jsoo/tests.otarget;
            shift;
            if [ "$1" = "-b" ]; then
                reload-browser \
                "http://`hostname`/mtime/test-jsoo/test_jsoo.html"
            fi
            ;;
        doc)     shift; pkg-doc -I src-os $* doc/dev-api.docdir ;;
        api-doc) shift; pkg-doc -I src-os $* doc/api.docdir ;;
        clean)   $OCAMLBUILD -clean ;;
        *)       $OCAMLBUILD $* ;;
    esac
}

if [ $# -eq 0 ];
then action default ;
else action $*; fi
